# Generated by Django 5.1.1 on 2024-11-10 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0008_rename_staff_id_notificationstaffs_stafff_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationstaffs",
            old_name="stafff_id",
            new_name="staff_id",
        ),
        migrations.RemoveField(
            model_name="students",
            name="course_id",
        ),
        migrations.AddField(
            model_name="students",
            name="courses",
            field=models.ManyToManyField(
                related_name="students", to="student_management_app.courses"
            ),
        ),
        migrations.AlterField(
            model_name="feedbackstaffs",
            name="feedback_reply",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedbackstudent",
            name="feedback_reply",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leavereportstaff",
            name="leave_status",
            field=models.IntegerField(
                choices=[(0, "Pending"), (1, "Approved"), (2, "Rejected")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="leavereportstudent",
            name="leave_status",
            field=models.IntegerField(
                choices=[(0, "Pending"), (1, "Approved"), (2, "Rejected")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="gender",
            field=models.CharField(
                choices=[("Male", "مرد"), ("Female", "زن")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="profile_pic",
            field=models.FileField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="subjects",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management_app.courses",
            ),
        ),
    ]
