# Generated by Django 5.1.1 on 2024-11-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_management_app",
            "0009_rename_stafff_id_notificationstaffs_staff_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationstaffs",
            old_name="staff_id",
            new_name="stafff_id",
        ),
        migrations.AlterField(
            model_name="feedbackstaffs",
            name="feedback_reply",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedbackstudent",
            name="feedback_reply",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="leavereportstaff",
            name="leave_status",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="leavereportstudent",
            name="leave_status",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="students",
            name="courses",
            field=models.ManyToManyField(
                blank=True, to="student_management_app.courses"
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="gender",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="students",
            name="profile_pic",
            field=models.FileField(default=1, upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subjects",
            name="course_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management_app.courses",
            ),
        ),
    ]
