# Generated by Django 5.1.1 on 2024-11-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_management_app",
            "0010_rename_staff_id_notificationstaffs_stafff_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                to="student_management_app.subjects",
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="gender",
            field=models.CharField(
                choices=[("male", "مرد"), ("female", "زن")], max_length=10
            ),
        ),
    ]
