# Generated by Django 5.1.1 on 2025-01-20 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0011_students_subjects_alter_students_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="gender",
            field=models.CharField(
                choices=[("male", "آقا"), ("female", "خانم")], max_length=10
            ),
        ),
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("attendance_date", models.DateField()),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_year_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.sessionyearmodel",
                    ),
                ),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="student_management_app.staffs",
                    ),
                ),
            ],
            options={
                "unique_together": {("staff_id", "attendance_date")},
            },
        ),
    ]
